name: adam_adamowicz
description: "Projeto sobre Adam Adamowicz, com biografia, jogos e informações sobre a empresa."

publish_to: 'none'  # Remova esta linha se quiser publicar no pub.dev

version: 1.0.0+1  # Versão do projeto (pode ser alterada conforme necessário)

environment:
  sdk: ">=3.5.4 <4.0.0"  # Garantir que o SDK Dart esteja correto

dependencies:
  flutter:
    sdk: flutter

  # Pacote para ícones estilo iOS
  cupertino_icons: ^1.0.8
  
  # Pacote para carrossel de imagens
  carousel_slider: ^4.0.0  # Confirme que esta versão funciona bem para o Flutter Web
  
  # Pacote para abrir URLs (como links externos)
  url_launcher: ^6.0.10  # Certifique-se de que esta versão seja compatível com Web também
  
  # Pacote para carregar imagens da rede com cache
  cached_network_image: ^3.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Conjunto de lints recomendados para boas práticas de código
  flutter_lints: ^4.0.0

# Configuração do Flutter para usar Material Design e outras opções
flutter:
  uses-material-design: true

  # Se necessário, adicione aqui a seção de assets para imagens
  assets:
    - assets/images/
    
  # Caso tenha fontes customizadas, adicione na seção fonts (caso contrário, remova)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
